project:
  type: website

website:
  title: "portfoliowebsite"
  navbar:
    left:
      - href: Project1.qmd
        text: Project 1
      - href: Project2.qmd
        text: Project 2
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

