project:
  type: website
  output-dir: docs

website:
  title: "portfoliowebsite"
  navbar: 
    left: 
      - href: index.qmd
        text: About Section
      - href: Project1.qmd
        text: Hospital Data Project
      - href: Project2.qmd
        text: Encelia Data Project
     
format:
  html:
    theme:  sandstone
    backgroundcolor: "lightblue"
    css: styles.css
    toc: true
editor: visual

